INSERT INTO permissions (code, description)
VALUES
  ('role.create', 'Create custom roles'),
  ('role.update', 'Edit custom roles'),
  ('role.delete', 'Delete or deactivate custom roles'),
  ('role.permission.assign', 'Assign permissions to roles'),
  ('staff.role.assign', 'Assign or revoke staff roles'),
  ('staff.user.read', 'View staff and customer user accounts'),
  ('staff.user.create', 'Create staff or customer user accounts'),
  ('staff.user.update', 'Edit staff or customer user accounts'),
  ('staff.user.delete', 'Deactivate staff or customer user accounts'),
  ('audit.read', 'View audit logs'),
  ('catalog.write', 'Create or update products and variants'),
  ('inventory.adjust', 'Adjust SKU inventory'),
  ('inventory.adjust.override', 'Override negative inventory adjustment guardrails'),
  ('inventory.transfer', 'Create and process inventory transfers'),
  ('order.read', 'View staff-visible orders'),
  ('order.ship', 'Mark orders shipped'),
  ('refund.process', 'Process refunds and returns'),
  ('promo.manage', 'Manage discount codes'),
  ('pos.sell', 'Create POS receipts and view POS sales'),
  ('pos.shift.manage', 'Open and close POS shifts'),
  ('invoice.manage', 'Create tax invoices and adjustment notes'),
  ('social.compose', 'Compose Instagram drafts'),
  ('social.connect', 'Connect or reconnect Instagram account'),
  ('customer.read', 'View customer profiles'),
  ('customer.write', 'Manage customer accounts'),
  ('report.read', 'View sales and inventory reports'),
  ('review.moderate', 'Approve or reject customer reviews'),
  ('inventory.cycle_count', 'Create and manage cycle counts')
ON CONFLICT (code) DO NOTHING;
