package com.seshop.audit.domain;

public enum AuditAction {
    USER_REGISTERED,
    USER_LOGGED_IN,
    ROLE_CREATED,
    ROLE_PERMISSION_ASSIGNED,
    USER_ROLE_ASSIGNED,
    USER_ROLE_REVOKED,
    INVENTORY_ADJUSTED,
    INVENTORY_TRANSFER_CHANGED,
    PAYMENT_CONFIRMED,
    REFUND_PROCESSED,
    POS_SHIFT_CLOSED,
    INSTAGRAM_CONNECTION_CHANGED,
    INVOICE_ISSUED
}
